server:
  port: 8087
env:
  dev
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Abcd1234_
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8
  jpa:
    show-sql: true
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule
