env: dev8
spring:
  application:
    name: order
  redis:
    host: 47.95.241.171
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Abcd1234_
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8
  jpa:
    show-sql: true
  zipkin:
    base-url: http://47.95.241.171:9411
  sleuth:
    sampler:
      percentage: 1
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule
management:
  endpoints:
    web:
      exposure:
        include: "*"
