PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule
env: dev8
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: user
  cloud:
    stream:
      bindings:
        theInputStream:
          group: theInputStream
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Abcd1234_
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 47.95.241.171
    password: 123456
    port: 5672
    username: springcloud
  redis:
    host: 47.95.241.171
    port: 6379

