env:
  dev
spring:
  application:
    name: user
  cloud: 
     stream:
      bindings:
        theInputStream: 
          group: theInputStream
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Abcd1234_
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 47.95.241.171
    port: 5672
    username: springcloud
    password: 123456
USER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule
